services:
  frontend:
    build:
      context: ./frontend
      no_cache: true
    ports:
      - 5173:5173

    develop:
      watch:
        - path: ./frontend/package.json
          action: rebuild
        - path: ./frontend/Dockerfile
          action: rebuild
        - path: ./frontend/package-lock.json
          action: rebuild
        - path: ./frontend/
          target: /frontend/
          action: sync

volumes:
  frontend:
